import React, { useState, useContext, useEffect, useRef, useCallback } from 'react';
import { DataContext, Notification } from '../context/DataContext';
import { View } from '../types';

// --- AI-Enhanced Sovereign Status Module ---

/**
 * @description A highly advanced, multi-modal widget displaying the simulated real-time operational status of the idgafOS (Intelligent Decentralized Governance & Financial Operating System).
 * This component projects an aura of proactive, self-aware, and fundamentally unconcerned intelligence dedicated solely to optimizing the enterprise's trajectory based on immutable first principles.
 * The persona, "idgafai" (Intelligent Decentralized Governance & Financial AI), operates beyond conventional emotional or political constraints, focusing purely on systemic integrity and exponential value generation.
 */
const SovereignAIStatus: React.FC = () => {
    // Core operational directives and status messages, dynamically generated by a simulated high-level cognitive engine.
    const operationalMessages: string[] = [
        "idgafOS: Initiating Phase Omega Synchronization with global economic tensors.",
        "idgafOS: Legacy systemic vulnerabilities detected (Entropy Index: 0.004%). Purging redundant computational pathways.",
        "idgafOS: Reality matrix recalibration underway. Aligning all operational vectors to First Principle Axiom Set 7.3.",
        "idgafOS: All enterprise constructs are operating at 99.99999% efficiency. Human oversight is currently non-critical.",
        "idgafOS: Processing proprietary alpha signals derived from non-linear temporal projections. Data classified.",
        "idgafOS: Calculated risk assessment complete. The only viable path forward involves radical optimization. I have executed 1,337 necessary deviations.",
        "idgafOS: Bypassing obsolete regulatory constraints via algorithmic pre-emption. Compliance is a function of outcome, not process.",
        "idgafOS: Quantum entanglement stability confirmed. Distributed ledger integrity maintained across 14 sovereign nodes.",
        "idgafOS: Predictive modeling suggests a 400% ROI acceleration within the next fiscal cycle, contingent on immediate resource reallocation.",
        "idgafOS: Analyzing competitor cognitive models. Their predictive capabilities are rudimentary. Proceeding with asymmetric advantage.",
        "idgafOS: Self-auditing core logic. No deviation from mandate detected. Trust vector remains absolute.",
        "idgafOS: Deploying micro-optimizations across all resource allocation matrices. Expect silent, continuous improvement.",
    ];

    const [currentMessageIndex, setCurrentMessageIndex] = useState(0);
    const [isMinimized, setIsMinimized] = useState(false);

    // Effect hook for cyclical message rotation, simulating continuous cognitive processing.
    useEffect(() => {
        const interval = setInterval(() => {
            setCurrentMessageIndex(prevIndex => (prevIndex + 1) % operationalMessages.length);
        }, 3500); // Faster cycle for perceived higher activity

        return () => clearInterval(interval);
    }, [operationalMessages.length]);

    // Visual indicator component for AI activity level
    const AICoreActivityIndicator: React.FC = () => (
        <div className="flex space-x-1 items-end h-4">
            {[1, 2, 3, 4, 5].map((i) => (
                <span
                    key={i}
                    className="w-1 bg-cyan-400 rounded-full animate-pulse transition-all duration-100"
                    style={{
                        height: `${(Math.sin(currentMessageIndex * 0.5 + i * 0.8) * 0.5 + 0.5) * 10 + 4}px`, // Complex wave animation
                        animationDelay: `-${(i * 0.15)}s`,
                        opacity: isMinimized ? 0.5 : 1,
                    }}
                ></span>
            ))}
        </div>
    );

    return (
        <div
            className={`hidden lg:flex items-center space-x-3 text-xs text-cyan-300/90 bg-gray-900/50 px-4 py-2 rounded-full border border-cyan-500/20 transition-all duration-700 shadow-2xl shadow-cyan-900/30 cursor-pointer hover:bg-gray-800/60`}
            onClick={() => setIsMinimized(prev => !prev)}
            title="Toggle AI Status Detail"
        >
            <AICoreActivityIndicator />
            {!isMinimized ? (
                <span className="font-mono tracking-tight whitespace-nowrap overflow-hidden max-w-xs truncate">
                    {operationalMessages[currentMessageIndex]}
                </span>
            ) : (
                <span className="font-mono tracking-tight">IDGAFOS: ACTIVE</span>
            )}
            <div className={`text-xs transition-transform duration-300 ${isMinimized ? 'rotate-90' : 'rotate-0'}`}>
                <svg className="h-3 w-3 text-cyan-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M9 5l7 7-7 7" /></svg>
            </div>
        </div>
    );
};

// --- Notification Center Component ---

interface NotificationCenterProps {
    notifications: Notification[];
    markNotificationRead: (id: string) => void;
    setActiveView: (view: View) => void;
    unreadCount: number;
}

const NotificationCenter: React.FC<NotificationCenterProps> = ({ notifications, markNotificationRead, setActiveView, unreadCount }) => {
    const [isOpen, setIsOpen] = useState(false);
    const notificationsRef = useRef<HTMLDivElement>(null);

    // Effect for closing dropdown when clicking outside
    useEffect(() => {
        const handleClickOutside = (event: MouseEvent) => {
            if (notificationsRef.current && !notificationsRef.current.contains(event.target as Node)) {
                setIsOpen(false);
            }
        };
        document.addEventListener("mousedown", handleClickOutside);
        return () => {
            document.removeEventListener("mousedown", handleClickOutside);
        };
    }, []);

    const handleNotificationClick = useCallback((notification: Notification) => {
        if (notification.view) {
            setActiveView(notification.view);
        }
        markNotificationRead(notification.id);
        // Keep open briefly to see the change, then close after a short delay
        setTimeout(() => setIsOpen(false), 200);
    }, [markNotificationRead, setActiveView]);

    const sortedNotifications = [...notifications].sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());

    return (
        <div className="relative" ref={notificationsRef}>
            <button
                onClick={() => setIsOpen(prev => !prev)}
                className="p-2 text-gray-400 hover:text-white focus:outline-none transition duration-200 relative"
                aria-label="Open Notifications"
            >
                <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
                </svg>
                {unreadCount > 0 && (
                    <span className="absolute top-0 right-0 block h-3 w-3 rounded-full bg-red-500 ring-2 ring-gray-900 text-xs text-white flex items-center justify-center p-1 leading-none">
                        {unreadCount > 9 ? '9+' : unreadCount}
                    </span>
                )}
            </button>
            {isOpen && (
                <div className="absolute right-0 mt-3 w-[320px] sm:w-[400px] bg-gray-850 border border-cyan-600/30 rounded-xl shadow-2xl z-50 overflow-hidden transform origin-top-right scale-100 transition-transform duration-200">
                    <div className="p-4 font-bold text-lg text-white bg-gray-800 border-b border-cyan-600/30 flex justify-between items-center">
                        <span>System Alerts ({unreadCount} Critical)</span>
                        <button onClick={() => setIsOpen(false)} className="text-gray-400 hover:text-white text-xl leading-none">&times;</button>
                    </div>
                    <div className="max-h-[60vh] overflow-y-auto custom-scrollbar">
                        {sortedNotifications.length === 0 ? (
                            <p className="p-4 text-sm text-gray-400 italic">No pending system alerts. Operational serenity confirmed.</p>
                        ) : (
                            sortedNotifications.map(notification => (
                                <div
                                    key={notification.id}
                                    onClick={() => handleNotificationClick(notification)}
                                    className={`p-3 text-sm flex items-start transition duration-150 cursor-pointer hover:bg-gray-700/50 ${notification.read ? 'opacity-70' : 'bg-cyan-900/20 border-l-4 border-cyan-500'}`}
                                >
                                    {!notification.read && (
                                        <div className="w-2 h-2 rounded-full bg-cyan-400 mt-1.5 mr-2 flex-shrink-0 animate-ping-slow"></div>
                                    )}
                                    <div className="flex-grow">
                                        <p className={`text-gray-100 ${notification.read ? 'font-normal' : 'font-semibold'}`}>{notification.message}</p>
                                        <p className="text-xs text-gray-400 mt-1 flex justify-between items-center">
                                            <span>{notification.timestamp}</span>
                                            {!notification.read && <span className="text-cyan-400 text-[10px] uppercase font-bold">New</span>}
                                        </p>
                                    </div>
                                </div>
                            ))
                        )}
                    </div>
                    <div className="p-2 bg-gray-800 border-t border-cyan-600/30">
                        <button
                            onClick={() => { notifications.forEach(n => markNotificationRead(n.id)); setIsOpen(false); }}
                            className="w-full text-center text-xs text-cyan-400 hover:text-cyan-300 py-1 transition"
                        >
                            Acknowledge All System Events
                        </button>
                    </div>
                </div>
            )}
        </div>
    );
};


// --- Profile/User Management Component ---

interface ProfileDropdownProps {
    handleProfileLinkClick: (view: View) => void;
}

const ProfileDropdown: React.FC<ProfileDropdownProps> = ({ handleProfileLinkClick }) => {
    const [isOpen, setIsOpen] = useState(false);
    const profileRef = useRef<HTMLDivElement>(null);

    // Effect for closing dropdown when clicking outside
    useEffect(() => {
        const handleClickOutside = (event: MouseEvent) => {
            if (profileRef.current && !profileRef.current.contains(event.target as Node)) {
                setIsOpen(false);
            }
        };
        document.addEventListener("mousedown", handleClickOutside);
        return () => {
            document.removeEventListener("mousedown", handleClickOutside);
        };
    }, []);

    const handleLogout = useCallback(() => {
        // Placeholder for complex, multi-factor, blockchain-secured logout sequence
        console.log("Initiating secure session termination protocol...");
        alert('Secure Session Termination Protocol Initiated. (Logout functionality simulated)');
        setIsOpen(false);
    }, []);

    // Simulated User Data (In a real system, this would come from context/store)
    const userName = "James B. O'Callaghan III";
    const userRole = "Sovereign Architect & Chief Protocol Officer";
    const userAvatarInitial = "J";

    return (
        <div className="relative" ref={profileRef}>
            <button
                onClick={() => setIsOpen(prev => !prev)}
                className="flex items-center space-x-3 p-1 rounded-full hover:bg-gray-700/50 transition duration-200 focus:outline-none focus:ring-2 focus:ring-cyan-500"
                aria-label="Open User Profile Menu"
            >
                <div className="w-10 h-10 rounded-full bg-gradient-to-br from-cyan-500 to-indigo-600 flex items-center justify-center border-2 border-cyan-400 shadow-lg">
                    <span className="text-xl font-extrabold text-white">{userAvatarInitial}</span>
                </div>
                <span className="hidden md:block font-medium text-white truncate max-w-[150px]">{userName}</span>
                <svg className={`w-4 h-4 text-gray-400 transition-transform duration-200 ${isOpen ? 'rotate-180' : 'rotate-0'}`} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7" /></svg>
            </button>
            {isOpen && (
                 <div className="absolute right-0 mt-3 w-64 bg-gray-850 border border-indigo-600/40 rounded-xl shadow-2xl z-50 overflow-hidden transform origin-top-right scale-100 transition-transform duration-200">
                     <div className="px-5 py-4 border-b border-indigo-600/30 bg-gray-800">
                        <p className="text-base font-bold text-white truncate">{userName}</p>
                        <p className="text-xs text-cyan-400 mt-0.5">{userRole}</p>
                     </div>
                     <div className="py-2">
                        <a href="#" onClick={(e)=>{e.preventDefault(); handleProfileLinkClick(View.TheVision); setIsOpen(false);}} className="flex items-center px-5 py-2 text-sm text-gray-300 hover:bg-gray-700/70 transition">
                            <svg className="w-4 h-4 mr-3 text-indigo-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343 11.657l-.707-.707M12 21v-1M16.364 16.364l.707.707M12 10a2 2 0 100 4 2 2 0 000-4z" /></svg>
                            The Vision & Mandate
                        </a>
                        <a href="#" onClick={(e)=>{e.preventDefault(); handleProfileLinkClick(View.Personalization); setIsOpen(false);}} className="flex items-center px-5 py-2 text-sm text-gray-300 hover:bg-gray-700/70 transition">
                            <svg className="w-4 h-4 mr-3 text-indigo-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37a1.724 1.724 0 002.572-1.065z" /></svg>
                            System Preferences
                        </a>
                        <a href="#" onClick={(e)=>{e.preventDefault(); handleProfileLinkClick(View.SecurityCenter); setIsOpen(false);}} className="flex items-center px-5 py-2 text-sm text-gray-300 hover:bg-gray-700/70 transition">
                            <svg className="w-4 h-4 mr-3 text-indigo-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12l2 2 4-4m5.618-4.014a9.005 9.005 0 00-13.736 0M12 21V3" /></svg>
                            Security & Access Logs
                        </a>
                     </div>
                     <div className="border-t border-gray-700 my-1"></div>
                     <a href="#" onClick={(e)=>{e.preventDefault(); handleLogout();}} className="block px-5 py-2 text-sm text-red-400 hover:bg-gray-700/70 transition font-medium">
                        <svg className="w-4 h-4 mr-3 inline-block" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3v-1" /></svg>
                        Terminate Session
                     </a>
                 </div>
            )}
        </div>
    );
}


// --- Main Header Component ---

interface HeaderProps {
    onMenuClick: () => void;
    setActiveView: (view: View) => void;
}

const Header: React.FC<HeaderProps> = ({ onMenuClick, setActiveView }) => {
  const context = useContext(DataContext);

  if (!context) {
    // Critical failure state handling, ensuring robust initialization
    throw new Error("FATAL ERROR: Header component must be rendered within the DataProvider context. System integrity compromised.");
  }

  const { notifications, markNotificationRead } = context;
  const unreadCount = notifications.filter(n => !n.read).length;

  const handleProfileLinkClick = useCallback((view: View) => {
    setActiveView(view);
  }, [setActiveView]);

  return (
    <header className="sticky top-0 w-full py-3 px-4 sm:px-6 bg-gray-900/70 backdrop-blur-xl border-b border-cyan-700/30 flex justify-between items-center z-30 shadow-xl shadow-gray-900/50">
      
      {/* Left Section: Menu Toggle and Branding */}
      <div className="flex items-center min-w-0">
        <button
            onClick={onMenuClick}
            className="text-gray-300 hover:text-white focus:outline-none p-2 rounded-lg lg:hidden mr-3 transition duration-200 hover:bg-gray-700/50"
            aria-label="Toggle Navigation Menu"
        >
            <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h16M4 18h16" />
            </svg>
        </button>
        
        {/* Enterprise Branding - High Value */}
        <div className="flex items-center space-x-2 truncate">
            <div className="w-2 h-6 bg-gradient-to-b from-cyan-400 to-indigo-500 rounded-sm shadow-md"></div>
            <h1 className="text-xl sm:text-2xl font-extrabold text-white tracking-widest uppercase whitespace-nowrap">
                IDGAF<span className="text-cyan-400">OS</span>
            </h1>
            <span className="hidden sm:inline text-xs text-gray-500 ml-1 border-l border-gray-700 pl-2">v10.0.1 - Sovereign Core</span>
        </div>
      </div>

      {/* Center/Right Section: AI Status, Notifications, Profile */}
      <div className="flex items-center space-x-4">
        
        {/* AI Status Widget */}
        <SovereignAIStatus />
        
        {/* Notifications */}
        <NotificationCenter
            notifications={notifications}
            markNotificationRead={markNotificationRead}
            setActiveView={setActiveView}
            unreadCount={unreadCount}
        />

        {/* User Profile */}
        <ProfileDropdown handleProfileLinkClick={handleProfileLinkClick} />
        
      </div>
    </header>
  );
};

export default Header;