/*
*
* Enterprise Financial Operating System (EFOS) Module: Joint Budget Tracker & AI Financial Intelligence Suite
*
* This module provides collaborative budgeting, real-time expense tracking, and advanced AI-driven financial forecasting and anomaly detection.
* It serves as a foundational component for the next-generation financial architecture, focusing on radical transparency and predictive optimization.
*
*/

import React, { useState, useMemo, useCallback } from 'react';

// --- TYPE DEFINITIONS: EXPANDED FOR ENTERPRISE AI INTEGRATION ---

/** Represents a single financial transaction or expense. */
interface Expense {
  id: string;
  description: string;
  amount: number;
  date: string;
  addedBy: string;
  status: 'Pending' | 'Approved' | 'Rejected';
  tags: string[];
  ai_risk_score: number; // 0.0 to 1.0, calculated by AI anomaly detection
}

/** Represents a budget category with allocation and associated expenses. */
interface Category {
  id: string;
  name: string;
  allocated: number;
  expenses: Expense[];
  budget_owner_id: string;
  ai_optimization_suggestion: string;
}

/** Represents a user within the collaborative system. */
interface User {
  id: string;
  name: string;
  role: 'Admin' | 'Contributor' | 'Auditor' | 'Executive';
  profile_status: 'Active' | 'Suspended';
  last_login: string;
}

/** Represents a Key Performance Indicator (KPI) tracked by the system. */
interface KPI {
  id: string;
  name: string;
  value: number;
  target: number;
  unit: string;
  trend: 'Up' | 'Down' | 'Stable';
  ai_insight: string;
}

/** Represents a predictive financial forecast generated by the AI model. */
interface AIForecast {
  month: string;
  projected_spent: number;
  confidence_level: number; // 0.0 to 1.0
  scenario_name: string;
  risk_factors: string[];
}

/** Represents a detected anomaly or suspicious activity. */
interface Anomaly {
  id: string;
  type: 'Overspend' | 'UnusualVendor' | 'DuplicateEntry' | 'HighRiskTransaction';
  expense_id: string;
  severity: 'Low' | 'Medium' | 'High' | 'Critical';
  resolution_status: 'Open' | 'Investigating' | 'Resolved';
  ai_explanation: string;
}

/** Represents a task generated for collaboration or resolution. */
interface CollaborationTask {
  id: string;
  title: string;
  assigned_to_id: string;
  due_date: string;
  priority: 'P1' | 'P2' | 'P3';
  status: 'To Do' | 'In Progress' | 'Done';
  related_entity_id: string; // Category or Expense ID
  ai_priority_reason: string;
}

/** Represents an entry in the immutable audit log. */
interface AuditEntry {
  timestamp: string;
  user_id: string;
  action: string;
  details: Record<string, any>;
  ai_verification_hash: string; // Simulated blockchain/integrity check
}

// --- MOCK DATA: EXPANDED ENTERPRISE DATA SETS ---

const mockUsers: User[] = [
  { id: 'user1', name: 'J. Oliver', role: 'Admin', profile_status: 'Active', last_login: '2023-11-01T10:00:00Z' },
  { id: 'user2', name: 'Sarah K.', role: 'Executive', profile_status: 'Active', last_login: '2023-11-01T09:30:00Z' },
  { id: 'user3', name: 'Michael B.', role: 'Contributor', profile_status: 'Active', last_login: '2023-10-31T15:00:00Z' },
  { id: 'user4', name: 'Audit AI', role: 'Auditor', profile_status: 'Active', last_login: '2023-11-01T00:00:00Z' },
];

const mockInitialCategories: Category[] = [
  {
    id: 'cat1',
    name: 'Operational Software Licenses',
    allocated: 50000,
    budget_owner_id: 'user1',
    ai_optimization_suggestion: 'Consider consolidating licenses for a 15% saving.',
    expenses: [
      { id: 'exp1', description: 'Q4 CRM Subscription Renewal', amount: 12500.50, date: '2023-10-26', addedBy: 'J. Oliver', status: 'Approved', tags: ['SaaS', 'Q4'], ai_risk_score: 0.1 },
      { id: 'exp2', description: 'AI Model Training Credits', amount: 4500.00, date: '2023-10-28', addedBy: 'Sarah K.', status: 'Approved', tags: ['AI', 'R&D'], ai_risk_score: 0.05 },
      { id: 'exp6', description: 'New Developer Tool Licenses', amount: 8000.00, date: '2023-10-29', addedBy: 'Michael B.', status: 'Pending', tags: ['Dev', 'Tools'], ai_risk_score: 0.4 },
    ],
  },
  {
    id: 'cat2',
    name: 'Cloud Infrastructure (AWS/Azure)',
    allocated: 75000,
    budget_owner_id: 'user2',
    ai_optimization_suggestion: 'High usage spike detected. Review serverless migration strategy.',
    expenses: [
      { id: 'exp3', description: 'AWS Compute Usage Oct 2023', amount: 35785.75, date: '2023-10-25', addedBy: 'J. Oliver', status: 'Approved', tags: ['Cloud', 'Infrastructure'], ai_risk_score: 0.2 },
      { id: 'exp4', description: 'Azure Storage Backup Fees', amount: 6000.00, date: '2023-10-20', addedBy: 'J. Oliver', status: 'Approved', tags: ['Cloud', 'Storage'], ai_risk_score: 0.1 },
    ],
  },
  {
    id: 'cat3',
    name: 'Marketing & Outreach',
    allocated: 30000,
    budget_owner_id: 'user3',
    ai_optimization_suggestion: 'Current ROI is 1.2x. Suggest increasing allocation by 10% for Q1.',
    expenses: [
      { id: 'exp5', description: 'Digital Ad Campaign Q4 Launch', amount: 15000.00, date: '2023-10-22', addedBy: 'Michael B.', status: 'Approved', tags: ['Marketing', 'Ads'], ai_risk_score: 0.08 },
      { id: 'exp7', description: 'Executive Travel for Conference', amount: 5500.00, date: '2023-10-30', addedBy: 'Sarah K.', status: 'Pending', tags: ['Travel', 'Conference'], ai_risk_score: 0.65 },
    ],
  },
];

const mockInitialTasks: CollaborationTask[] = [
  { id: 'task1', title: 'Review Q4 CRM Renewal Terms', assigned_to_id: 'user1', due_date: '2023-11-15', priority: 'P1', status: 'To Do', related_entity_id: 'cat1', ai_priority_reason: 'High contractual impact and imminent deadline.' },
  { id: 'task2', title: 'Investigate Cloud Infrastructure Spike', assigned_to_id: 'user2', due_date: '2023-11-08', priority: 'P1', status: 'In Progress', related_entity_id: 'cat2', ai_priority_reason: 'Directly impacts operational stability and budget overrun risk.' },
  { id: 'task3', title: 'Approve Executive Travel Expense (exp7)', assigned_to_id: 'user1', due_date: '2023-11-05', priority: 'P2', status: 'To Do', related_entity_id: 'exp7', ai_priority_reason: 'Requires Admin approval before month-end close.' },
];

// --- AI SIMULATION CORE LOGIC (Using deterministic functions to simulate complex models) ---

/**
 * Helper function to generate a stable, pseudo-random hash for audit integrity.
 * @param data - The data object to hash.
 * @returns A simulated verification hash string.
 */
const generateAIVerificationHash = (data: any): string => {
  const jsonString = JSON.stringify(data);
  let hash = 0;
  for (let i = 0; i < jsonString.length; i++) {
    const char = jsonString.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash |= 0; // Convert to 32bit integer
  }
  return `AI_HASH_${Math.abs(hash).toString(16).toUpperCase()}`;
};

/**
 * Simulates an AI model generating a 12-month financial forecast.
 * This function uses current spending trends and mock risk factors.
 * @param categories - Current budget categories.
 * @returns An array of AIForecast objects.
 */
const simulateAIForecast = (categories: Category[]): AIForecast[] => {
  const baseSpent = categories.reduce((sum, cat) => sum + cat.expenses.reduce((expSum, exp) => expSum + exp.amount, 0), 0);
  const totalAllocated = categories.reduce((sum, cat) => sum + cat.allocated, 0);
  const monthlyBase = baseSpent / 3; // Assuming 3 months of data for base calculation

  const forecasts: AIForecast[] = [];
  const months = ['Nov 2023', 'Dec 2023', 'Jan 2024', 'Feb 2024', 'Mar 2024', 'Apr 2024', 'May 2024', 'Jun 2024', 'Jul 2024', 'Aug 2024', 'Sep 2024', 'Oct 2024'];

  months.forEach((month, index) => {
    let projected = monthlyBase * (1 + (index * 0.02)); // 2% growth trend
    let confidence = 0.95 - (index * 0.05);
    let riskFactors: string[] = [];

    if (index === 2) { // Q1 start spike
      projected *= 1.15;
      riskFactors.push('Q1 Software Renewal Spike');
      confidence -= 0.1;
    }
    if (projected > totalAllocated * 0.4) {
      riskFactors.push('Potential Quarterly Overrun');
    }

    forecasts.push({
      month,
      projected_spent: Math.round(projected * 100) / 100,
      confidence_level: Math.max(0.5, Math.round(confidence * 100) / 100),
      scenario_name: 'Base Growth Scenario',
      risk_factors: riskFactors,
    });
  });

  return forecasts;
};

/**
 * Simulates AI anomaly detection across all expenses.
 * @param categories - Current budget categories.
 * @returns An array of detected Anomaly objects.
 */
const runAnomalyDetection = (categories: Category[]): Anomaly[] => {
  const anomalies: Anomaly[] = [];
  let anomalyIdCounter = 100;

  categories.forEach(cat => {
    cat.expenses.forEach(exp => {
      // Rule 1: High Risk Score (Simulated)
      if (exp.ai_risk_score > 0.6) {
        anomalies.push({
          id: `anom${anomalyIdCounter++}`,
          type: 'HighRiskTransaction',
          expense_id: exp.id,
          severity: exp.ai_risk_score > 0.8 ? 'Critical' : 'High',
          resolution_status: 'Open',
          ai_explanation: `Risk score of ${exp.ai_risk_score} is 3 standard deviations above category mean. Requires immediate review.`,
        });
      }

      // Rule 2: Unusual Vendor/Description (Simulated based on keywords)
      if (exp.description.toLowerCase().includes('travel') && exp.amount > 5000) {
        anomalies.push({
          id: `anom${anomalyIdCounter++}`,
          type: 'UnusualVendor',
          expense_id: exp.id,
          severity: 'Medium',
          resolution_status: 'Investigating',
          ai_explanation: `Large travel expense detected (${formatCurrency(exp.amount)}). Verify compliance with corporate policy.`,
        });
      }
    });
  });

  return anomalies;
};

/**
 * Simulates AI generating complex KPIs based on current data.
 * @param summary - Budget summary data.
 * @param categories - Current budget categories.
 * @returns An array of KPI objects.
 */
const generateFinancialKPIs = (summary: { totalAllocated: number, totalSpent: number, remaining: number }): KPI[] => {
  const utilizationRate = summary.totalAllocated > 0 ? (summary.totalSpent / summary.totalAllocated) : 0;
  const burnRate = summary.totalSpent / 30; // Simulated daily burn rate

  return [
    {
      id: 'kpi1',
      name: 'Budget Utilization Rate',
      value: utilizationRate * 100,
      target: 85,
      unit: '%',
      trend: utilizationRate > 0.5 ? 'Up' : 'Stable',
      ai_insight: `Current utilization is ${Math.round(utilizationRate * 100)}%. Model suggests optimal range is 80-90% for efficiency.`,
    },
    {
      id: 'kpi2',
      name: 'Daily Cash Burn Rate',
      value: burnRate,
      target: 5000,
      unit: 'USD',
      trend: burnRate > 6000 ? 'Up' : 'Stable',
      ai_insight: `Average daily spend is ${formatCurrency(burnRate)}. Monitor closely if this exceeds target threshold.`,
    },
    {
      id: 'kpi3',
      name: 'High Risk Transaction Ratio',
      value: 2, // Mock value: 2 high risk transactions found
      target: 0,
      unit: 'Count',
      trend: 'Up',
      ai_insight: 'Two high-risk anomalies detected. Immediate action required to maintain financial integrity.',
    },
  ];
};

// --- HELPER FUNCTIONS (Expanded) ---

const formatCurrency = (amount: number) => {
  return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(amount);
};

const formatDate = (dateString: string) => {
  return new Date(dateString).toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
};

// --- SUB-COMPONENTS: UI PRIMITIVES ---

interface ProgressBarProps {
  value: number;
  max: number;
  height?: string;
}

const ProgressBar: React.FC<ProgressBarProps> = ({ value, max, height = '10px' }) => {
  const percentage = max > 0 ? (value / max) * 100 : 0;
  const color = percentage > 100 ? '#e53e3e' : percentage > 85 ? '#dd6b20' : '#38a169';

  return (
    <div style={{ ...styles.progressBarContainer, height }}>
      <div style={{ ...styles.progressBarFill, width: `${Math.min(percentage, 100)}%`, backgroundColor: color }} />
    </div>
  );
};

interface StatusBadgeProps {
  status: 'Pending' | 'Approved' | 'Rejected' | 'Open' | 'Resolved' | 'To Do' | 'In Progress' | 'Done';
}

const StatusBadge: React.FC<StatusBadgeProps> = ({ status }) => {
  const getStyle = (s: string) => {
    switch (s) {
      case 'Approved':
      case 'Resolved':
      case 'Done':
        return { backgroundColor: '#38a169', color: 'white' };
      case 'Pending':
      case 'In Progress':
      case 'Investigating':
      case 'To Do':
        return { backgroundColor: '#f6e05e', color: '#2d3748' };
      case 'Rejected':
      case 'Open':
        return { backgroundColor: '#e53e3e', color: 'white' };
      default:
        return { backgroundColor: '#e2e8f0', color: '#4a5568' };
    }
  };

  return (
    <span style={{ ...styles.statusBadge, ...getStyle(status) }}>
      {status}
    </span>
  );
};

// --- FEATURE COMPONENTS: AI & ENTERPRISE FOCUS ---

interface AIPredictiveForecastingProps {
  forecasts: AIForecast[];
}

/**
 * Component displaying AI-generated financial forecasts.
 * Includes scenario analysis and confidence metrics.
 */
const AIPredictiveForecasting: React.FC<AIPredictiveForecastingProps> = ({ forecasts }) => {
  const [selectedScenario, setSelectedScenario] = useState(forecasts[0]?.scenario_name || 'Base Growth Scenario');

  const filteredForecasts = useMemo(() => {
    return forecasts.filter(f => f.scenario_name === selectedScenario);
  }, [forecasts, selectedScenario]);

  const totalProjectedSpend = useMemo(() => {
    return filteredForecasts.reduce((sum, f) => sum + f.projected_spent, 0);
  }, [filteredForecasts]);

  return (
    <div style={styles.aiCard}>
      <h3 style={styles.aiTitle}>AI Predictive Forecasting (12 Months)</h3>
      <div style={styles.forecastControls}>
        <label style={styles.label}>Scenario:</label>
        <select
          value={selectedScenario}
          onChange={(e) => setSelectedScenario(e.target.value)}
          style={styles.inputSmall}
        >
          {/* In a real app, scenarios would be dynamic. Mocking one here. */}
          <option value="Base Growth Scenario">Base Growth Scenario</option>
          <option value="High Investment Scenario">High Investment Scenario (Simulated)</option>
        </select>
      </div>

      <div style={styles.forecastSummary}>
        <p><strong>Total Projected Spend:</strong> {formatCurrency(totalProjectedSpend)}</p>
        <p><strong>Average Confidence:</strong> {Math.round(filteredForecasts.reduce((sum, f) => sum + f.confidence_level, 0) / filteredForecasts.length * 100)}%</p>
      </div>

      <div style={styles.forecastGrid}>
        {filteredForecasts.map((f, index) => (
          <div key={index} style={styles.forecastItem}>
            <h4 style={styles.forecastMonth}>{f.month}</h4>
            <p style={styles.forecastValue}>{formatCurrency(f.projected_spent)}</p>
            <ProgressBar value={f.confidence_level * 100} max={100} height="5px" />
            <span style={styles.confidenceText}>Confidence: {Math.round(f.confidence_level * 100)}%</span>
            {f.risk_factors.length > 0 && (
              <div style={styles.riskFactors}>
                {f.risk_factors.map((risk, i) => (
                  <span key={i} style={styles.riskBadge}>{risk}</span>
                ))}
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
};

interface AnomalyDetectionDashboardProps {
  anomalies: Anomaly[];
  onResolve: (id: string) => void;
}

/**
 * Component for reviewing and managing AI-detected financial anomalies.
 */
const AnomalyDetectionDashboard: React.FC<AnomalyDetectionDashboardProps> = ({ anomalies, onResolve }) => {
  const openAnomalies = useMemo(() => anomalies.filter(a => a.resolution_status !== 'Resolved'), [anomalies]);

  const handleResolve = useCallback((id: string) => {
    // In a real application, this would update the backend state.
    // Here, we simulate the action.
    if (window.confirm(`Mark anomaly ${id} as Resolved?`)) {
      onResolve(id);
    }
  }, [onResolve]);

  return (
    <div style={styles.aiCard}>
      <h3 style={styles.aiTitle}>AI Anomaly Detection & Risk Management</h3>
      <p style={styles.anomalySummary}>
        Total Open Anomalies: <strong style={{ color: openAnomalies.length > 0 ? '#e53e3e' : '#38a169' }}>{openAnomalies.length}</strong>
      </p>

      <div style={styles.anomalyListContainer}>
        {openAnomalies.length === 0 ? (
          <p style={styles.noAnomalyMessage}>No critical anomalies detected. System integrity is high.</p>
        ) : (
          openAnomalies.map(anomaly => (
            <div key={anomaly.id} style={styles.anomalyItem}>
              <div style={styles.anomalyHeader}>
                <span style={{ ...styles.anomalySeverity, backgroundColor: anomaly.severity === 'Critical' ? '#c53030' : anomaly.severity === 'High' ? '#dd6b20' : '#ecc94b' }}>
                  {anomaly.severity}
                </span>
                <h4 style={styles.anomalyTitle}>{anomaly.type} - Expense ID: {anomaly.expense_id}</h4>
                <StatusBadge status={anomaly.resolution_status as any} />
              </div>
              <p style={styles.anomalyExplanation}>
                <strong>AI Explanation:</strong> {anomaly.ai_explanation}
              </p>
              <div style={styles.anomalyActions}>
                <button onClick={() => handleResolve(anomaly.id)} style={styles.resolveButton}>
                  Mark as Resolved
                </button>
                <button style={styles.investigateButton}>
                  Initiate Audit Trail
                </button>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
};

interface FinancialKPIsDashboardProps {
  kpis: KPI[];
}

/**
 * Component displaying Key Performance Indicators with AI insights.
 */
const FinancialKPIsDashboard: React.FC<FinancialKPIsDashboardProps> = ({ kpis }) => {
  return (
    <div style={styles.kpiDashboard}>
      <h3 style={styles.aiTitle}>Executive Financial KPIs</h3>
      <div style={styles.kpiGrid}>
        {kpis.map(kpi => (
          <div key={kpi.id} style={styles.kpiCard}>
            <h4 style={styles.kpiName}>{kpi.name}</h4>
            <p style={styles.kpiValue}>
              {kpi.unit === 'USD' ? formatCurrency(kpi.value) : `${Math.round(kpi.value * 10) / 10}${kpi.unit}`}
            </p>
            <div style={styles.kpiTrend}>
              Trend: <span style={{ color: kpi.trend === 'Up' ? '#38a169' : kpi.trend === 'Down' ? '#e53e3e' : '#4a5568' }}>{kpi.trend}</span>
            </div>
            <p style={styles.kpiInsight}>
              <strong style={{ color: '#4299e1' }}>AI Insight:</strong> {kpi.ai_insight}
            </p>
          </div>
        ))}
      </div>
    </div>
  );
};

interface CollaborationTaskManagementProps {
  tasks: CollaborationTask[];
  users: User[];
  onUpdateTaskStatus: (taskId: string, status: 'To Do' | 'In Progress' | 'Done') => void;
}

/**
 * Component for managing collaborative tasks, prioritized by AI.
 */
const CollaborationTaskManagement: React.FC<CollaborationTaskManagementProps> = ({ tasks, users, onUpdateTaskStatus }) => {
  const [filterStatus, setFilterStatus] = useState<'All' | 'To Do' | 'In Progress' | 'Done'>('To Do');

  const filteredTasks = useMemo(() => {
    if (filterStatus === 'All') return tasks;
    return tasks.filter(t => t.status === filterStatus);
  }, [tasks, filterStatus]);

  const getUserName = (id: string) => users.find(u => u.id === id)?.name || 'Unknown User';

  const getPriorityStyle = (priority: 'P1' | 'P2' | 'P3') => {
    switch (priority) {
      case 'P1': return { backgroundColor: '#e53e3e', color: 'white' };
      case 'P2': return { backgroundColor: '#dd6b20', color: 'white' };
      case 'P3': return { backgroundColor: '#38a169', color: 'white' };
      default: return {};
    }
  };

  return (
    <div style={styles.aiCard}>
      <h3 style={styles.aiTitle}>AI-Prioritized Collaboration Tasks</h3>
      <div style={styles.taskControls}>
        <button
          onClick={() => setFilterStatus('To Do')}
          style={{ ...styles.taskFilterButton, backgroundColor: filterStatus === 'To Do' ? '#4299e1' : '#e2e8f0' }}
        >
          To Do ({tasks.filter(t => t.status === 'To Do').length})
        </button>
        <button
          onClick={() => setFilterStatus('In Progress')}
          style={{ ...styles.taskFilterButton, backgroundColor: filterStatus === 'In Progress' ? '#4299e1' : '#e2e8f0' }}
        >
          In Progress ({tasks.filter(t => t.status === 'In Progress').length})
        </button>
        <button
          onClick={() => setFilterStatus('All')}
          style={{ ...styles.taskFilterButton, backgroundColor: filterStatus === 'All' ? '#4299e1' : '#e2e8f0' }}
        >
          All
        </button>
      </div>

      <div style={styles.taskListContainer}>
        {filteredTasks.length === 0 ? (
          <p style={styles.noAnomalyMessage}>No tasks matching the current filter.</p>
        ) : (
          filteredTasks.map(task => (
            <div key={task.id} style={styles.taskItem}>
              <div style={styles.taskHeader}>
                <span style={{ ...styles.taskPriority, ...getPriorityStyle(task.priority) }}>
                  {task.priority}
                </span>
                <h4 style={styles.taskTitle}>{task.title}</h4>
                <StatusBadge status={task.status} />
              </div>
              <div style={styles.taskDetails}>
                <span>Assigned to: <strong>{getUserName(task.assigned_to_id)}</strong></span>
                <span>Due: {formatDate(task.due_date)}</span>
              </div>
              <p style={styles.taskAiReason}>
                <strong>AI Priority Reason:</strong> {task.ai_priority_reason}
              </p>
              <div style={styles.taskActions}>
                {task.status !== 'Done' && (
                  <select
                    value={task.status}
                    onChange={(e) => onUpdateTaskStatus(task.id, e.target.value as any)}
                    style={styles.taskStatusSelect}
                  >
                    <option value="To Do">To Do</option>
                    <option value="In Progress">In Progress</option>
                    <option value="Done">Done</option>
                  </select>
                )}
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
};

interface AIChatAssistantProps {
  categories: Category[];
  currentUser: User;
}

/**
 * Simulated AI Chat Assistant for natural language budget queries.
 */
const AIChatAssistant: React.FC<AIChatAssistantProps> = ({ categories, currentUser }) => {
  const [input, setInput] = useState('');
  const [chatHistory, setChatHistory] = useState<{ sender: 'User' | 'AI', message: string }[]>([
    { sender: 'AI', message: `Hello ${currentUser.name}. I am EFOS AI Assistant. How can I assist with your budget analysis today? Try asking: "What is the risk score for Cloud Infrastructure?"` }
  ]);

  const handleSendMessage = useCallback(() => {
    if (!input.trim()) return;

    const userMessage = input.trim();
    setChatHistory(prev => [...prev, { sender: 'User', message: userMessage }]);
    setInput('');

    // --- AI NLP Simulation Logic ---
    let aiResponse = "I'm sorry, I couldn't process that specific query. Please try rephrasing or ask about categories, expenses, or forecasts.";

    const lowerMessage = userMessage.toLowerCase();

    if (lowerMessage.includes('risk score') && lowerMessage.includes('cloud')) {
      const cloudCat = categories.find(c => c.name.includes('Cloud Infrastructure'));
      if (cloudCat) {
        const totalSpent = cloudCat.expenses.reduce((sum, exp) => sum + exp.amount, 0);
        const riskScore = totalSpent / cloudCat.allocated;
        aiResponse = `The current simulated risk score for Cloud Infrastructure is ${Math.round(riskScore * 100)}%. This is primarily due to high utilization (${formatCurrency(totalSpent)} spent out of ${formatCurrency(cloudCat.allocated)} allocated). The AI suggests reviewing task T2.`;
      }
    } else if (lowerMessage.includes('optimization') || lowerMessage.includes('save money')) {
      const suggestions = categories.map(c => c.ai_optimization_suggestion).join('; ');
      aiResponse = `Based on current trends, the AI suggests the following optimization strategies: ${suggestions}`;
    } else if (lowerMessage.includes('pending expenses')) {
      const pendingCount = categories.flatMap(c => c.expenses).filter(e => e.status === 'Pending').length;
      aiResponse = `There are currently ${pendingCount} expenses pending approval across all categories.`;
    }

    setTimeout(() => {
      setChatHistory(prev => [...prev, { sender: 'AI', message: aiResponse }]);
    }, 1500);

  }, [input, categories]);

  return (
    <div style={styles.aiChatContainer}>
      <h3 style={styles.aiTitle}>EFOS AI Assistant</h3>
      <div style={styles.chatHistory}>
        {chatHistory.map((chat, index) => (
          <div key={index} style={chat.sender === 'User' ? styles.userMessage : styles.aiMessage}>
            <strong>{chat.sender}:</strong> {chat.message}
          </div>
        ))}
      </div>
      <div style={styles.chatInputArea}>
        <input
          type="text"
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyPress={(e) => { if (e.key === 'Enter') handleSendMessage(); }}
          placeholder="Ask the AI about your budget..."
          style={styles.chatInput}
        />
        <button onClick={handleSendMessage} style={styles.chatSendButton}>Send</button>
      </div>
    </div>
  );
};

interface AuditLogViewerProps {
  auditLog: AuditEntry[];
}

/**
 * Component for viewing the immutable, AI-verified audit log.
 */
const AuditLogViewer: React.FC<AuditLogViewerProps> = ({ auditLog }) => {
  const [visibleEntries, setVisibleEntries] = useState(10);

  const loadMore = useCallback(() => {
    setVisibleEntries(prev => prev + 10);
  }, []);

  return (
    <div style={styles.aiCard}>
      <h3 style={styles.aiTitle}>Immutable Audit Log (AI Verified)</h3>
      <div style={styles.auditLogContainer}>
        <div style={styles.auditLogHeader}>
          <span style={{ width: '20%' }}>Timestamp</span>
          <span style={{ width: '15%' }}>User ID</span>
          <span style={{ width: '30%' }}>Action</span>
          <span style={{ width: '35%' }}>AI Verification Hash</span>
        </div>
        {auditLog.slice(0, visibleEntries).map((entry, index) => (
          <div key={index} style={styles.auditLogItem}>
            <span style={{ width: '20%' }}>{formatDate(entry.timestamp)}</span>
            <span style={{ width: '15%' }}>{entry.user_id}</span>
            <span style={{ width: '30%', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{entry.action}</span>
            <span style={{ width: '35%', fontSize: '0.7rem', color: '#38a169' }}>{entry.ai_verification_hash}</span>
          </div>
        ))}
        {auditLog.length > visibleEntries && (
          <button onClick={loadMore} style={styles.loadMoreButton}>Load More ({auditLog.length - visibleEntries} remaining)</button>
        )}
      </div>
    </div>
  );
};

// --- MAIN COMPONENT: JOINT BUDGET TRACKER (EFOS DASHBOARD) ---

const JointBudgetTracker: React.FC = () => {
  const [categories, setCategories] = useState<Category[]>(mockInitialCategories);
  const [currentUser, setCurrentUser] = useState<User>(mockUsers[0]);
  const [tasks, setTasks] = useState<CollaborationTask[]>(mockInitialTasks);
  const [auditLog, setAuditLog] = useState<AuditEntry[]>([]);

  const [showAddExpenseModal, setShowAddExpenseModal] = useState(false);
  const [showManageCategoryModal, setShowManageCategoryModal] = useState(false);
  const [selectedCategory, setSelectedCategory] = useState<Category | null>(null);
  const [activeTab, setActiveTab] = useState<'Budget' | 'AI Dashboard' | 'Collaboration' | 'Audit'>('Budget');

  // --- CORE COMPUTATIONS & AI HOOKS ---

  const budgetSummary = useMemo(() => {
    const totalAllocated = categories.reduce((sum, cat) => sum + cat.allocated, 0);
    const totalSpent = categories.reduce((sum, cat) =>
      sum + cat.expenses.reduce((expSum, exp) => expSum + exp.amount, 0), 0);
    return { totalAllocated, totalSpent, remaining: totalAllocated - totalSpent };
  }, [categories]);

  const aiForecasts = useMemo(() => simulateAIForecast(categories), [categories]);
  const anomalies = useMemo(() => runAnomalyDetection(categories), [categories]);
  const kpis = useMemo(() => generateFinancialKPIs(budgetSummary), [budgetSummary]);

  // --- AUDIT LOGGING FUNCTION ---
  const logAction = useCallback((action: string, details: Record<string, any>) => {
    const entry: AuditEntry = {
      timestamp: new Date().toISOString(),
      user_id: currentUser.id,
      action,
      details,
      ai_verification_hash: generateAIVerificationHash({ action, details, timestamp: Date.now() }),
    };
    setAuditLog(prev => [entry, ...prev]);
  }, [currentUser.id]);

  // --- HANDLERS ---

  const handleAddExpense = useCallback((categoryId: string, newExpense: Omit<Expense, 'id' | 'status' | 'tags' | 'ai_risk_score'>) => {
    const expenseWithAI: Expense = {
      ...newExpense,
      id: `exp-${Date.now()}`,
      status: 'Pending', // New expenses require approval
      tags: newExpense.description.split(' ').filter(w => w.length > 3),
      ai_risk_score: Math.random() * 0.5, // Initial low risk score
    };

    setCategories(prevCategories =>
      prevCategories.map(cat =>
        cat.id === categoryId
          ? { ...cat, expenses: [...cat.expenses, expenseWithAI] }
          : cat
      )
    );
    setShowAddExpenseModal(false);
    logAction('Expense Added', { categoryId, amount: expenseWithAI.amount, description: expenseWithAI.description });
  }, [logAction]);

  const handleSaveCategory = useCallback((categoryData: { id?: string; name: string; allocated: number }) => {
    if (categoryData.id) { // Editing existing category
      setCategories(prev => prev.map(cat => cat.id === categoryData.id ? { ...cat, name: categoryData.name, allocated: categoryData.allocated } : cat));
      logAction('Category Updated', { categoryId: categoryData.id, name: categoryData.name, allocated: categoryData.allocated });
    } else { // Adding new category
      const newCategory: Category = {
        id: `cat-${Date.now()}`,
        name: categoryData.name,
        allocated: categoryData.allocated,
        expenses: [],
        budget_owner_id: currentUser.id,
        ai_optimization_suggestion: 'New category added. AI requires 3 months of data for optimization suggestions.',
      };
      setCategories(prev => [...prev, newCategory]);
      logAction('Category Added', { categoryId: newCategory.id, name: newCategory.name });
    }
    setShowManageCategoryModal(false);
    setSelectedCategory(null);
  }, [logAction, currentUser.id]);

  const handleDeleteCategory = useCallback((categoryId: string) => {
    if (window.confirm('Are you sure you want to delete this category and all its expenses? This action is logged.')) {
        setCategories(prev => prev.filter(cat => cat.id !== categoryId));
        logAction('Category Deleted', { categoryId });
    }
  }, [logAction]);

  const handleUpdateTaskStatus = useCallback((taskId: string, status: 'To Do' | 'In Progress' | 'Done') => {
    setTasks(prev => prev.map(t => t.id === taskId ? { ...t, status } : t));
    logAction('Task Status Updated', { taskId, newStatus: status });
  }, [logAction]);

  const handleResolveAnomaly = useCallback((anomalyId: string) => {
    // Simulate updating the anomaly status (which would typically be stored in a separate state/DB)
    // For simplicity here, we just log the resolution.
    logAction('Anomaly Resolved', { anomalyId, resolvedBy: currentUser.name });
  }, [logAction, currentUser.name]);

  const switchUser = () => {
    const nextUser = currentUser.id === 'user1' ? mockUsers[1] : mockUsers[0];
    setCurrentUser(nextUser);
    logAction('User Switched', { newUserId: nextUser.id });
  };

  const getCategorySpent = (category: Category) => {
    return category.expenses.reduce((sum, exp) => sum + exp.amount, 0);
  };

  const isAdmin = currentUser.role === 'Admin' || currentUser.role === 'Executive';

  // --- RENDER SUB-COMPONENTS FOR BUDGET TAB ---

  const renderBudgetCategories = () => (
    <main style={styles.categoriesList}>
      {categories.map(category => {
        const spent = getCategorySpent(category);
        const remaining = category.allocated - spent;
        const owner = mockUsers.find(u => u.id === category.budget_owner_id)?.name || 'N/A';

        return (
          <div key={category.id} style={styles.categoryCard}>
            <div style={styles.categoryHeader}>
              <h3 style={styles.categoryName}>{category.name}</h3>
              <span style={styles.categoryOwner}>Owner: {owner}</span>
              {isAdmin && (
                <div style={styles.categoryActions}>
                  <button onClick={() => { setSelectedCategory(category); setShowManageCategoryModal(true); }} style={styles.editButton}>Edit</button>
                  <button onClick={() => handleDeleteCategory(category.id)} style={styles.deleteButton}>Delete</button>
                </div>
              )}
            </div>
            <div style={styles.categoryBody}>
              <div style={styles.categoryStats}>
                <span>Spent: {formatCurrency(spent)}</span>
                <span>Allocated: {formatCurrency(category.allocated)}</span>
              </div>
              <ProgressBar value={spent} max={category.allocated} />
              <div style={{ ...styles.categoryRemaining, color: remaining >= 0 ? '#4a5568' : '#e53e3e' }}>
                {formatCurrency(remaining)} {remaining >= 0 ? 'remaining' : 'overspent'}
              </div>

              <p style={styles.aiSuggestionText}>
                <strong style={{ color: '#4299e1' }}>AI Optimization:</strong> {category.ai_optimization_suggestion}
              </p>

              <h4 style={styles.expenseListTitle}>Recent Expenses & Risk Scores:</h4>
              <ul style={styles.expenseList}>
                {category.expenses.length > 0 ? (
                  category.expenses
                    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
                    .slice(0, 5) // Show last 5
                    .map(exp => (
                      <li key={exp.id} style={styles.expenseItem}>
                        <div style={{ display: 'flex', flexDirection: 'column', flexGrow: 1 }}>
                          <span style={{ fontWeight: 600 }}>{exp.description}</span>
                          <span style={{ fontSize: '0.75rem', color: '#718096' }}>{formatDate(exp.date)} by {exp.addedBy}</span>
                        </div>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                          <StatusBadge status={exp.status} />
                          <span style={{ color: exp.ai_risk_score > 0.5 ? '#e53e3e' : '#38a169', fontWeight: 700 }}>
                            Risk: {Math.round(exp.ai_risk_score * 100)}%
                          </span>
                          <span>{formatCurrency(exp.amount)}</span>
                        </div>
                      </li>
                    ))
                ) : (
                  <li style={styles.noExpenseItem}>No expenses yet.</li>
                )}
              </ul>
            </div>
          </div>
        );
      })}
    </main>
  );

  // --- MAIN RENDER ---

  return (
    <div style={styles.container}>
      <header style={styles.header}>
        <h1 style={styles.title}>EFOS: AI Financial Intelligence Suite</h1>
        <div style={styles.userControls}>
          <span style={styles.currentUserInfo}>
            Logged in as: <strong>{currentUser.name}</strong> ({currentUser.role})
          </span>
          <button onClick={switchUser} style={styles.switchUserButton}>Switch User</button>
        </div>
      </header>

      {/* --- NAVIGATION TABS --- */}
      <nav style={styles.navTabs}>
        {['Budget', 'AI Dashboard', 'Collaboration', 'Audit'].map(tab => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab as any)}
            style={{
              ...styles.navTabButton,
              ...(activeTab === tab ? styles.navTabActive : {})
            }}
          >
            {tab}
          </button>
        ))}
      </nav>

      {/* --- CONTENT AREA --- */}
      <div style={styles.contentArea}>
        {activeTab === 'Budget' && (
          <>
            {/* SUMMARY SECTION */}
            <section style={styles.summarySection}>
              <div style={styles.summaryCard}>
                <h3 style={styles.summaryTitle}>Total Allocated</h3>
                <p style={styles.summaryValue}>{formatCurrency(budgetSummary.totalAllocated)}</p>
              </div>
              <div style={styles.summaryCard}>
                <h3 style={styles.summaryTitle}>Total Spent</h3>
                <p style={styles.summaryValue}>{formatCurrency(budgetSummary.totalSpent)}</p>
              </div>
              <div style={styles.summaryCard}>
                <h3 style={styles.summaryTitle}>Remaining Capital</h3>
                <p style={{...styles.summaryValue, color: budgetSummary.remaining >= 0 ? '#38a169' : '#e53e3e'}}>
                  {formatCurrency(budgetSummary.remaining)}
                </p>
              </div>
              <div style={styles.summaryCard}>
                <h3 style={styles.summaryTitle}>Pending Approvals</h3>
                <p style={{...styles.summaryValue, color: '#dd6b20'}}>
                  {categories.flatMap(c => c.expenses).filter(e => e.status === 'Pending').length} Items
                </p>
              </div>
            </section>

            {/* CONTROLS */}
            <div style={styles.controls}>
              <button onClick={() => setShowAddExpenseModal(true)} style={styles.primaryButton}>Add Expense</button>
              {isAdmin && (
                  <button onClick={() => { setSelectedCategory(null); setShowManageCategoryModal(true); }} style={styles.secondaryButton}>
                  Add Category
                  </button>
              )}
            </div>

            {/* CATEGORIES LIST */}
            {renderBudgetCategories()}
          </>
        )}

        {activeTab === 'AI Dashboard' && (
          <div style={styles.aiDashboardGrid}>
            <FinancialKPIsDashboard kpis={kpis} />
            <AIPredictiveForecasting forecasts={aiForecasts} />
            <AnomalyDetectionDashboard anomalies={anomalies} onResolve={handleResolveAnomaly} />
            <AIChatAssistant categories={categories} currentUser={currentUser} />
          </div>
        )}

        {activeTab === 'Collaboration' && (
          <CollaborationTaskManagement
            tasks={tasks}
            users={mockUsers}
            onUpdateTaskStatus={handleUpdateTaskStatus}
          />
        )}

        {activeTab === 'Audit' && (
          <AuditLogViewer auditLog={auditLog} />
        )}
      </div>


      {/* --- MODALS --- */}
      {showAddExpenseModal && (
        <AddExpenseModal
          categories={categories}
          currentUser={currentUser}
          onClose={() => setShowAddExpenseModal(false)}
          onSave={handleAddExpense}
        />
      )}
       {showManageCategoryModal && isAdmin && (
        <ManageCategoryModal
          category={selectedCategory}
          onClose={() => {setShowManageCategoryModal(false); setSelectedCategory(null);}}
          onSave={handleSaveCategory}
        />
      )}
    </div>
  );
};

// --- MODAL COMPONENTS (Detailed) ---

interface AddExpenseModalProps {
  categories: Category[];
  currentUser: User;
  onClose: () => void;
  onSave: (categoryId: string, newExpense: Omit<Expense, 'id' | 'status' | 'tags' | 'ai_risk_score'>) => void;
}

const AddExpenseModal: React.FC<AddExpenseModalProps> = ({ categories, currentUser, onClose, onSave }) => {
  const [description, setDescription] = useState('');
  const [amount, setAmount] = useState('');
  const [date, setDate] = useState(new Date().toISOString().split('T')[0]);
  const [categoryId, setCategoryId] = useState(categories.length > 0 ? categories[0].id : '');
  const [error, setError] = useState('');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const parsedAmount = parseFloat(amount);
    if (!description || !amount || isNaN(parsedAmount) || parsedAmount <= 0 || !categoryId || !date) {
      setError('Please ensure all fields are filled correctly.');
      return;
    }
    onSave(categoryId, {
      description,
      amount: parsedAmount,
      date: date,
      addedBy: currentUser.name,
    });
  };

  return (
    <div style={styles.modalBackdrop}>
      <div style={styles.modalContent}>
        <h2 style={styles.modalTitle}>Add New Enterprise Expense</h2>
        {error && <p style={styles.errorMessage}>{error}</p>}
        <form onSubmit={handleSubmit}>
          <div style={styles.formGroup}>
            <label htmlFor="description" style={styles.label}>Description (AI Categorization Input)</label>
            <input
              id="description"
              type="text"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              style={styles.input}
              placeholder="e.g., Q1 Server Maintenance Contract"
              required
            />
          </div>
          <div style={styles.formRow}>
            <div style={{ ...styles.formGroup, flex: 1 }}>
              <label htmlFor="amount" style={styles.label}>Amount (USD)</label>
              <input
                id="amount"
                type="number"
                value={amount}
                onChange={(e) => setAmount(e.target.value)}
                style={styles.input}
                step="0.01"
                min="0.01"
                required
              />
            </div>
            <div style={{ ...styles.formGroup, flex: 1 }}>
              <label htmlFor="date" style={styles.label}>Transaction Date</label>
              <input
                id="date"
                type="date"
                value={date}
                onChange={(e) => setDate(e.target.value)}
                style={styles.input}
                required
              />
            </div>
          </div>
          <div style={styles.formGroup}>
            <label htmlFor="category" style={styles.label}>Budget Category</label>
            <select
              id="category"
              value={categoryId}
              onChange={(e) => setCategoryId(e.target.value)}
              style={styles.input}
              required
            >
              {categories.map(cat => (
                <option key={cat.id} value={cat.id}>{cat.name}</option>
              ))}
            </select>
          </div>
          <p style={styles.modalFooterNote}>
            Note: All new expenses are automatically flagged for AI risk assessment and require {currentUser.role === 'Admin' ? 'Executive' : 'Admin'} approval.
          </p>
          <div style={styles.modalActions}>
            <button type="button" onClick={onClose} style={styles.secondaryButton}>Cancel</button>
            <button type="submit" style={styles.primaryButton}>Submit Expense for Approval</button>
          </div>
        </form>
      </div>
    </div>
  );
};

interface ManageCategoryModalProps {
    category: Category | null;
    onClose: () => void;
    onSave: (data: { id?: string; name: string; allocated: number }) => void;
}

const ManageCategoryModal: React.FC<ManageCategoryModalProps> = ({ category, onClose, onSave }) => {
    const [name, setName] = useState(category?.name || '');
    const [allocated, setAllocated] = useState(category?.allocated.toString() || '');
    const [error, setError] = useState('');

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        const parsedAllocated = parseFloat(allocated);
        if (!name || !allocated || isNaN(parsedAllocated) || parsedAllocated < 0) {
            setError('Please fill all fields with valid values.');
            return;
        }
        onSave({ id: category?.id, name, allocated: parsedAllocated });
    };

    return (
        <div style={styles.modalBackdrop}>
            <div style={styles.modalContent}>
                <h2 style={styles.modalTitle}>{category ? 'Edit Budget Category' : 'Add New Budget Category'}</h2>
                {error && <p style={styles.errorMessage}>{error}</p>}
                <form onSubmit={handleSubmit}>
                    <div style={styles.formGroup}>
                        <label htmlFor="categoryName" style={styles.label}>Category Name</label>
                        <input
                            id="categoryName"
                            type="text"
                            value={name}
                            onChange={(e) => setName(e.target.value)}
                            style={styles.input}
                            required
                        />
                    </div>
                    <div style={styles.formGroup}>
                        <label htmlFor="allocatedAmount" style={styles.label}>Allocated Annual Budget (USD)</label>
                        <input
                            id="allocatedAmount"
                            type="number"
                            value={allocated}
                            onChange={(e) => setAllocated(e.target.value)}
                            style={styles.input}
                            step="1"
                            min="0"
                            required
                        />
                    </div>
                    <p style={styles.modalFooterNote}>
                        Setting a new budget triggers an AI review of historical spending patterns to ensure feasibility.
                    </p>
                    <div style={styles.modalActions}>
                        <button type="button" onClick={onClose} style={styles.secondaryButton}>Cancel</button>
                        <button type="submit" style={styles.primaryButton}>Save Category</button>
                    </div>
                </form>
            </div>
        </div>
    );
};

// --- STYLES (Massively Expanded for Enterprise UI) ---
const styles: { [key: string]: React.CSSProperties } = {
  // Global Container and Layout
  container: {
    fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
    backgroundColor: '#f8f9fa',
    padding: '3rem',
    borderRadius: '12px',
    maxWidth: '1600px',
    margin: '2rem auto',
    color: '#343a40',
    boxShadow: '0 10px 30px rgba(0, 0, 0, 0.05)',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1.5rem',
    borderBottom: '2px solid #e9ecef',
    paddingBottom: '1.5rem',
  },
  title: {
    fontSize: '2.5rem',
    fontWeight: 700,
    color: '#007bff',
  },
  userControls: {
    display: 'flex',
    alignItems: 'center',
    gap: '1.5rem',
  },
  currentUserInfo: {
    fontSize: '1rem',
    color: '#6c757d',
  },
  switchUserButton: {
    padding: '0.6rem 1.2rem',
    fontSize: '0.9rem',
    backgroundColor: '#6c757d',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
  },

  // Navigation Tabs
  navTabs: {
    display: 'flex',
    marginBottom: '2rem',
    borderBottom: '1px solid #dee2e6',
  },
  navTabButton: {
    padding: '1rem 1.5rem',
    fontSize: '1.1rem',
    fontWeight: 500,
    backgroundColor: 'transparent',
    border: 'none',
    borderBottom: '3px solid transparent',
    cursor: 'pointer',
    color: '#6c757d',
    transition: 'all 0.3s',
  },
  navTabActive: {
    color: '#007bff',
    borderBottom: '3px solid #007bff',
    backgroundColor: '#f1f3f5',
  },
  contentArea: {
    paddingTop: '1rem',
  },

  // Summary Section
  summarySection: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '2rem',
    marginBottom: '2rem',
  },
  summaryCard: {
    backgroundColor: '#ffffff',
    padding: '2rem',
    borderRadius: '10px',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.08)',
    borderLeft: '5px solid #007bff',
  },
  summaryTitle: {
    margin: '0 0 0.75rem 0',
    fontSize: '1.1rem',
    color: '#495057',
    fontWeight: 500,
  },
  summaryValue: {
    margin: 0,
    fontSize: '2.2rem',
    fontWeight: 700,
    color: '#212529',
  },

  // Controls
  controls: {
    display: 'flex',
    gap: '1.5rem',
    marginBottom: '2rem',
  },
  primaryButton: {
    backgroundColor: '#007bff',
    color: 'white',
    border: 'none',
    padding: '0.8rem 1.8rem',
    borderRadius: '8px',
    fontSize: '1rem',
    cursor: 'pointer',
    fontWeight: 600,
    transition: 'background-color 0.2s',
  },
  secondaryButton: {
    backgroundColor: '#e9ecef',
    color: '#343a40',
    border: '1px solid #ced4da',
    padding: '0.8rem 1.8rem',
    borderRadius: '8px',
    fontSize: '1rem',
    cursor: 'pointer',
    fontWeight: 600,
    transition: 'background-color 0.2s',
  },

  // Categories List
  categoriesList: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(450px, 1fr))',
    gap: '2rem',
  },
  categoryCard: {
    backgroundColor: '#ffffff',
    borderRadius: '10px',
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.05)',
    overflow: 'hidden',
    border: '1px solid #f1f3f5',
  },
  categoryHeader: {
    padding: '1.2rem 1.8rem',
    borderBottom: '1px solid #e9ecef',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#f8f9fa',
  },
  categoryName: {
    margin: 0,
    fontSize: '1.4rem',
    fontWeight: 600,
    color: '#212529',
  },
  categoryOwner: {
    fontSize: '0.85rem',
    color: '#6c757d',
    marginLeft: '1rem',
  },
  categoryActions: {
    display: 'flex',
    gap: '0.75rem',
  },
  editButton: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: '#007bff',
    fontSize: '0.9rem',
    fontWeight: 500,
  },
  deleteButton: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: '#dc3545',
    fontSize: '0.9rem',
    fontWeight: 500,
  },
  categoryBody: {
    padding: '1.8rem',
  },
  categoryStats: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '1rem',
    fontSize: '1rem',
    fontWeight: 500,
    color: '#495057',
  },
  progressBarContainer: {
    width: '100%',
    backgroundColor: '#e9ecef',
    borderRadius: '5px',
    height: '12px',
    overflow: 'hidden',
    marginBottom: '0.5rem',
  },
  progressBarFill: {
    height: '100%',
    borderRadius: '5px',
    transition: 'width 0.3s ease-in-out',
  },
  categoryRemaining: {
    textAlign: 'right',
    marginTop: '0.75rem',
    fontSize: '1.1rem',
    fontWeight: 600,
  },
  aiSuggestionText: {
    marginTop: '1.5rem',
    padding: '1rem',
    backgroundColor: '#e6f7ff',
    borderLeft: '4px solid #007bff',
    borderRadius: '4px',
    fontSize: '0.9rem',
    color: '#495057',
  },
  expenseListTitle: {
    marginTop: '2rem',
    marginBottom: '1rem',
    fontSize: '1.1rem',
    color: '#212529',
    borderBottom: '1px solid #e9ecef',
    paddingBottom: '0.5rem',
    fontWeight: 600,
  },
  expenseList: {
    listStyle: 'none',
    padding: 0,
    margin: 0,
    maxHeight: '250px',
    overflowY: 'auto',
  },
  expenseItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '0.75rem 0',
    borderBottom: '1px dashed #dee2e6',
    fontSize: '0.95rem',
  },
  noExpenseItem: {
    color: '#adb5bd',
    padding: '0.75rem 0',
    fontStyle: 'italic',
  },
  statusBadge: {
    padding: '0.3rem 0.6rem',
    borderRadius: '4px',
    fontSize: '0.75rem',
    fontWeight: 600,
    textTransform: 'uppercase',
  },

  // Modals
  modalBackdrop: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2000,
  },
  modalContent: {
    backgroundColor: 'white',
    padding: '2.5rem',
    borderRadius: '10px',
    width: '95%',
    maxWidth: '600px',
    boxShadow: '0 10px 25px rgba(0, 0, 0, 0.2)',
  },
  modalTitle: {
    fontSize: '1.75rem',
    marginBottom: '1.5rem',
    borderBottom: '1px solid #e9ecef',
    paddingBottom: '0.5rem',
    color: '#212529',
  },
  formGroup: {
    marginBottom: '1.5rem',
  },
  formRow: {
    display: 'flex',
    gap: '1.5rem',
  },
  label: {
    display: 'block',
    marginBottom: '0.5rem',
    fontWeight: 600,
    color: '#495057',
    fontSize: '0.95rem',
  },
  input: {
    width: '100%',
    padding: '0.8rem',
    border: '1px solid #ced4da',
    borderRadius: '6px',
    fontSize: '1rem',
    boxSizing: 'border-box',
    transition: 'border-color 0.2s',
  },
  inputSmall: {
    padding: '0.5rem',
    border: '1px solid #ced4da',
    borderRadius: '6px',
    fontSize: '0.9rem',
  },
  modalActions: {
    marginTop: '2rem',
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '1rem',
  },
  errorMessage: {
      color: '#dc3545',
      backgroundColor: '#f8d7da',
      padding: '1rem',
      borderRadius: '6px',
      border: '1px solid #f5c6cb',
      marginBottom: '1.5rem',
  },
  modalFooterNote: {
    fontSize: '0.85rem',
    color: '#6c757d',
    marginTop: '1rem',
    borderTop: '1px solid #e9ecef',
    paddingTop: '1rem',
  },

  // AI Dashboard Specific Styles
  aiDashboardGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '2rem',
  },
  aiCard: {
    backgroundColor: '#ffffff',
    padding: '2rem',
    borderRadius: '10px',
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.05)',
    borderLeft: '4px solid #17a2b8',
    gridColumn: 'span 2',
  },
  aiTitle: {
    fontSize: '1.5rem',
    fontWeight: 600,
    color: '#17a2b8',
    marginBottom: '1.5rem',
    borderBottom: '1px solid #e9ecef',
    paddingBottom: '0.5rem',
  },

  // Forecasting Styles
  forecastControls: {
    marginBottom: '1.5rem',
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  forecastSummary: {
    backgroundColor: '#f1f3f5',
    padding: '1rem',
    borderRadius: '6px',
    marginBottom: '1.5rem',
    border: '1px solid #dee2e6',
  },
  forecastGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '1.5rem',
  },
  forecastItem: {
    padding: '1rem',
    border: '1px solid #ced4da',
    borderRadius: '8px',
    backgroundColor: '#ffffff',
  },
  forecastMonth: {
    margin: '0 0 0.5rem 0',
    fontSize: '1rem',
    color: '#495057',
  },
  forecastValue: {
    fontSize: '1.25rem',
    fontWeight: 700,
    color: '#212529',
    marginBottom: '0.5rem',
  },
  confidenceText: {
    fontSize: '0.8rem',
    color: '#6c757d',
    marginTop: '0.5rem',
    display: 'block',
  },
  riskFactors: {
    marginTop: '0.5rem',
  },
  riskBadge: {
    display: 'inline-block',
    backgroundColor: '#ffc107',
    color: '#343a40',
    padding: '0.2rem 0.5rem',
    borderRadius: '4px',
    fontSize: '0.7rem',
    marginRight: '0.5rem',
  },

  // Anomaly Styles
  anomalySummary: {
    fontSize: '1.1rem',
    marginBottom: '1.5rem',
  },
  anomalyListContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  anomalyItem: {
    border: '1px solid #f5c6cb',
    backgroundColor: '#f8d7da',
    padding: '1rem',
    borderRadius: '8px',
  },
  anomalyHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    marginBottom: '0.75rem',
  },
  anomalySeverity: {
    padding: '0.4rem 0.8rem',
    borderRadius: '6px',
    fontWeight: 700,
    fontSize: '0.8rem',
    color: 'white',
  },
  anomalyTitle: {
    margin: 0,
    flexGrow: 1,
    fontSize: '1.1rem',
    color: '#721c24',
  },
  anomalyExplanation: {
    fontSize: '0.9rem',
    color: '#721c24',
    marginBottom: '1rem',
    paddingLeft: '0.5rem',
    borderLeft: '3px solid #dc3545',
  },
  anomalyActions: {
    display: 'flex',
    gap: '1rem',
    justifyContent: 'flex-end',
  },
  resolveButton: {
    ...styles.secondaryButton,
    padding: '0.5rem 1rem',
    backgroundColor: '#28a745',
    color: 'white',
    border: 'none',
  },
  investigateButton: {
    ...styles.secondaryButton,
    padding: '0.5rem 1rem',
    backgroundColor: '#ffc107',
    color: '#343a40',
    border: 'none',
  },
  noAnomalyMessage: {
    textAlign: 'center',
    padding: '2rem',
    backgroundColor: '#e9f7ef',
    borderRadius: '8px',
    color: '#28a745',
    border: '1px solid #c3e6cb',
  },

  // KPI Styles
  kpiDashboard: {
    gridColumn: 'span 2',
    ...styles.aiCard,
  },
  kpiGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '1.5rem',
  },
  kpiCard: {
    padding: '1.5rem',
    border: '1px solid #dee2e6',
    borderRadius: '8px',
    backgroundColor: '#f8f9fa',
  },
  kpiName: {
    fontSize: '1rem',
    color: '#495057',
    marginBottom: '0.5rem',
  },
  kpiValue: {
    fontSize: '1.8rem',
    fontWeight: 700,
    color: '#007bff',
    margin: '0 0 0.5rem 0',
  },
  kpiTrend: {
    fontSize: '0.9rem',
    fontWeight: 500,
    marginBottom: '1rem',
  },
  kpiInsight: {
    fontSize: '0.85rem',
    color: '#6c757d',
    borderTop: '1px dashed #ced4da',
    paddingTop: '0.75rem',
  },

  // Collaboration Styles
  taskControls: {
    display: 'flex',
    gap: '1rem',
    marginBottom: '1.5rem',
  },
  taskFilterButton: {
    padding: '0.6rem 1.2rem',
    borderRadius: '6px',
    border: 'none',
    cursor: 'pointer',
    fontWeight: 600,
    transition: 'background-color 0.2s',
  },
  taskListContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  taskItem: {
    border: '1px solid #ced4da',
    padding: '1rem',
    borderRadius: '8px',
    backgroundColor: '#ffffff',
  },
  taskHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    marginBottom: '0.5rem',
  },
  taskPriority: {
    padding: '0.3rem 0.6rem',
    borderRadius: '4px',
    fontSize: '0.75rem',
    fontWeight: 700,
  },
  taskTitle: {
    margin: 0,
    flexGrow: 1,
    fontSize: '1.1rem',
    color: '#212529',
  },
  taskDetails: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '0.9rem',
    color: '#6c757d',
    marginBottom: '0.75rem',
  },
  taskAiReason: {
    fontSize: '0.85rem',
    backgroundColor: '#f1f3f5',
    padding: '0.75rem',
    borderRadius: '4px',
    borderLeft: '3px solid #17a2b8',
  },
  taskActions: {
    marginTop: '1rem',
    textAlign: 'right',
  },
  taskStatusSelect: {
    padding: '0.5rem',
    borderRadius: '6px',
    border: '1px solid #ced4da',
  },

  // AI Chat Styles
  aiChatContainer: {
    gridColumn: 'span 1',
    ...styles.aiCard,
    display: 'flex',
    flexDirection: 'column',
    height: '500px',
    padding: '1.5rem',
  },
  chatHistory: {
    flexGrow: 1,
    overflowY: 'auto',
    padding: '1rem',
    border: '1px solid #e9ecef',
    borderRadius: '6px',
    marginBottom: '1rem',
    backgroundColor: '#f8f9fa',
  },
  userMessage: {
    textAlign: 'right',
    marginBottom: '0.75rem',
    padding: '0.5rem 1rem',
    backgroundColor: '#007bff',
    color: 'white',
    borderRadius: '15px 15px 0 15px',
    maxWidth: '80%',
    marginLeft: 'auto',
  },
  aiMessage: {
    textAlign: 'left',
    marginBottom: '0.75rem',
    padding: '0.5rem 1rem',
    backgroundColor: '#e9ecef',
    color: '#343a40',
    borderRadius: '15px 15px 15px 0',
    maxWidth: '80%',
    marginRight: 'auto',
  },
  chatInputArea: {
    display: 'flex',
    gap: '0.5rem',
  },
  chatInput: {
    ...styles.input,
    flexGrow: 1,
    padding: '0.75rem',
  },
  chatSendButton: {
    ...styles.primaryButton,
    padding: '0.75rem 1.5rem',
  },

  // Audit Log Styles
  auditLogContainer: {
    maxHeight: '600px',
    overflowY: 'auto',
    border: '1px solid #e9ecef',
    borderRadius: '8px',
  },
  auditLogHeader: {
    display: 'flex',
    padding: '1rem',
    backgroundColor: '#f1f3f5',
    fontWeight: 600,
    borderBottom: '2px solid #dee2e6',
    position: 'sticky',
    top: 0,
    zIndex: 10,
  },
  auditLogItem: {
    display: 'flex',
    padding: '0.75rem 1rem',
    borderBottom: '1px solid #e9ecef',
    fontSize: '0.85rem',
  },
  loadMoreButton: {
    width: '100%',
    padding: '1rem',
    backgroundColor: '#e9ecef',
    border: 'none',
    cursor: 'pointer',
    fontWeight: 600,
    color: '#495057',
    borderTop: '1px solid #dee2e6',
  }
};

export default JointBudgetTracker;